[build]
  command = "pip install -r requirements.txt"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
